# Project name, used to register with JumpServer purely for identification, must not be duplicated
# NAME: {{ Hostname }}

# The JumpServer project's URL, used for API request registration
CORE_HOST: http://127.0.0.1:8080

# Bootstrap Token, a pre-shared key used to register the service account and terminal
# Must match the value in JumpServer's config file; can be removed after registration completes
BOOTSTRAP_TOKEN: <PleasgeChangeSameWithJumpserver>

# IP to bind to on startup, default 0.0.0.0
# BIND_HOST: 0.0.0.0

# HTTP/WS listen port, default 8081
# HTTPD_PORT: 8081

# Log level [DEBUG, INFO, WARN, ERROR, FATAL, CRITICAL]
# LOG_LEVEL: INFO

# Guacamole Server IP, default 127.0.0.1
# GUA_HOST: 127.0.0.1

# Guacamole Server port, default 4822
# GUA_PORT: 4822

# Session sharing type [local, redis], default local
# SHARE_ROOM_TYPE: local

# Redis configuration
# REDIS_HOST: 127.0.0.1
# REDIS_PORT: 6379
# REDIS_PASSWORD:
# REDIS_DB_ROOM:
